FROM mcr.microsoft.com/dotnet/aspnet:6.0

COPY publish/ /root/

# allow all users access to this so we can run container as non root.
# create /root/tmp if nonexistent
RUN chmod -R 755 /root && mkdir /root/tmp

WORKDIR /root/

ENV ASPNETCORE_URLS="http://*:4545"
EXPOSE 4545/tcp
ENTRYPOINT ["dotnet", "Requestrr.WebApi.dll"]
